# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_用户session'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='备注',
            field=models.CharField(default='', max_length=1024, verbose_name='备注：用户信息备注，比如全名'),
        ),
    ]
