# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-16 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='一句话',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('时间', models.DateTimeField(default=django.utils.timezone.now, verbose_name='备注： ')),
                ('来源', models.CharField(default='', max_length=100, verbose_name='备注： ')),
                ('内容', models.CharField(default='', max_length=2048, verbose_name='备注： ')),
                ('确认', models.CharField(default='N', max_length=20, verbose_name='备注：')),
            ],
        ),
    ]
