# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-17 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneword', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='一句话',
            name='关联用户',
            field=models.CharField(default='admin', max_length=2048, verbose_name='备注：消息属于哪些用户的'),
        ),
    ]
