# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-15 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='备份表',
            name='时间',
        ),
        migrations.RemoveField(
            model_name='备份表',
            name='来源',
        ),
        migrations.AddField(
            model_name='备份表',
            name='备份日期',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='备注:'),
        ),
        migrations.AddField(
            model_name='备份表',
            name='备份时间',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='备注： '),
        ),
        migrations.AddField(
            model_name='备份表',
            name='备份来源',
            field=models.CharField(default='', max_length=20, verbose_name='备注： '),
        ),
        migrations.AlterField(
            model_name='备份表',
            name='备份文件',
            field=models.CharField(default='', max_length=2048, verbose_name='备注： '),
        ),
        migrations.AlterField(
            model_name='备份表',
            name='备份状态',
            field=models.CharField(default='N', max_length=20, verbose_name='备注：'),
        ),
    ]
