# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-15 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_auto_20180815_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='备份表',
            name='备份日期',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='备注:'),
        ),
        migrations.AlterField(
            model_name='备份表',
            name='备份时间',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='备注： '),
        ),
    ]
