# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-15 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_auto_20180815_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='备份表',
            name='确认状态',
            field=models.CharField(default='N', max_length=20, verbose_name='备注：'),
        ),
    ]
