# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0005_备份表_备份主机'),
    ]

    operations = [
        migrations.CreateModel(
            name='备份项目',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('备份项目', models.CharField(max_length=1024, null=True, verbose_name='用于配置需要备份的项目')),
            ],
        ),
        migrations.AddField(
            model_name='备份表',
            name='备份项目',
            field=models.CharField(max_length=1024, null=True, verbose_name='用于配置需要备份的项目'),
        ),
    ]
