# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='消息',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('时间', models.DateTimeField(default=django.utils.timezone.now, verbose_name='备注： 消息时间')),
                ('来源', models.CharField(max_length=20, verbose_name='备注： 来自哪个主机ip')),
                ('消息', models.CharField(default='', max_length=20, verbose_name='备注：消息内容')),
                ('状态', models.CharField(default='N', max_length=20, verbose_name='备注：是否被确认')),
            ],
        ),
    ]
