# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='消息',
            name='时间',
            field=models.DateTimeField(verbose_name='备注： 消息时间'),
        ),
    ]
