# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0002_auto_20171206_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='消息',
            name='时间',
            field=models.CharField(max_length=50, verbose_name='备注： 消息时间'),
        ),
    ]
