# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0003_auto_20171211_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='消息',
            name='消息',
            field=models.CharField(default='', max_length=2048, verbose_name='备注：消息内容'),
        ),
    ]
