# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0005_auto_20171225_0851'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='消息',
            unique_together=set([('时间', '来源', '消息')]),
        ),
    ]
