# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0006_auto_20171225_0856'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='消息',
            name='msgs_消息_时间_9f6243_idx',
        ),
        migrations.AddIndex(
            model_name='消息',
            index=models.Index(fields=['时间', '来源'], name='时间_来源_idx'),
        ),
    ]
