# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0007_auto_20171225_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='备份主机',
            name='主机备注',
            field=models.TextField(default='空', max_length=2048, verbose_name='主机备注'),
        ),
    ]
