# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0008_备份主机_主机备注'),
    ]

    operations = [
        migrations.CreateModel(
            name='人',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('姓名', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='工程师',
            fields=[
                ('人_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='msgs.人')),
            ],
            bases=('msgs.人',),
        ),
    ]
