# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0009_人_工程师'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='工程师',
            name='人_ptr',
        ),
        migrations.DeleteModel(
            name='人',
        ),
        migrations.DeleteModel(
            name='工程师',
        ),
    ]
