# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0011_工程师'),
    ]

    operations = [
        migrations.CreateModel(
            name='存储',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('文件id', models.IntegerField(verbose_name='文件ID')),
                ('上载', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
