# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0012_存储'),
    ]

    operations = [
        migrations.AddField(
            model_name='消息',
            name='文件',
            field=models.CharField(default='', max_length=2048, verbose_name='备注： 来自哪个文件'),
        ),
    ]
