# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0013_消息_文件'),
    ]

    operations = [
        migrations.AddField(
            model_name='消息',
            name='关联用户',
            field=models.CharField(default='wxl', max_length=2048, verbose_name='备注：消息属于哪些用户的'),
        ),
    ]
