# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0014_消息_关联用户'),
    ]

    operations = [
        migrations.AlterField(
            model_name='消息',
            name='关联用户',
            field=models.CharField(default='admin', max_length=2048, verbose_name='备注：消息属于哪些用户的'),
        ),
    ]
